[bayesian_optimization]
b = [[0.0, 0.05], [0.0, 15.0], [0.0, 20.0]]

[bayesian_optimization.setup]
eval_metric = "FSS"
init_points = 30
n_iter = 70
random_state = "None"
decimal_precision = 2
verbose = 2

[medslik2.sim_extent]
SIM_NAME = "syria"
sim_length = "0008"
duration = "0000"
spillrate = "00027.78"
age = "0"
grid_size = "150.0"
oil_api = 28.0
oil_volume = 2000.0
number_slick = 151

[medslik2.sim_date]
day = "24"
month = "08"
year = "21"
hour = "08"
minutes = "10"

[medslik2.sim_coords]
lat_degree = 35
lat_minutes = 15.6
lon_degree = 35
lon_minutes = 54.6
delta = 1

[medslik2.sim_params]
k = [ "Wind correction (Drift Factor)", "Horizontal Diffusivity"]
v = [ 0.01, 10.26]
kparticles = "No of parcels used to model diffusion and dispersion"
vparticles = 90000

[medslik2.data_format]
type = "analysis"
time_res = "day"
process_files = "True"
